### ISSUE TITLE
Undefined method config for Object:Class with upgrade to 4.0

### ISSUE THREAD

**Issue by siruguri** [fredjean/middleman-s3_sync#106]
Upgrading to Middleman S3 Sync 3.4.1 seems to be causing an error. I am not sure if this is some sort of version incompatibility - here's what I have on my system:

* ruby 2.1.5p273
* middleman 3.4 (I had also tried this with middleman 3.3)

When I use Middleman S3 Sync 3.3 I don't see any errors. With 4.0, I get the error below. My `config.rb` is basically the default you get out of `midldeman init` and I am using just the three main variables needed for authenticated access to S3 - bucket, access key and secret.

```
# middleman s3_sync
/Users/sameer/.rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.12/lib/middleman-core/application.rb:191:in `initialize': undefined method `config' for Object:Class (NoMethodError)
	from /Users/sameer/.rvm/gems/ruby-2.1.5/gems/middleman-s3_sync-4.0.0/lib/middleman-s3_sync/commands.rb:58:in `new'
	from /Users/sameer/.rvm/gems/ruby-2.1.5/gems/middleman-s3_sync-4.0.0/lib/middleman-s3_sync/commands.rb:58:in `s3_sync'
	from /Users/sameer/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/sameer/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/sameer/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/sameer/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/sameer/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/sameer/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/sameer/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/sameer/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /Users/sameer/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
	from /Users/sameer/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/sameer/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/sameer/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/sameer/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/sameer/.rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.12/lib/middleman-core/cli.rb:20:in `start'
	from /Users/sameer/.rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.12/bin/middleman:18:in `<top (required)>'
	from /Users/sameer/.rvm/gems/ruby-2.1.5/bin/middleman:23:in `load'
	from /Users/sameer/.rvm/gems/ruby-2.1.5/bin/middleman:23:in `<main>'
	from /Users/sameer/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/sameer/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'

# bundle exec gem which middleman-s3_sync
/Users/sameer/.rvm/gems/ruby-2.1.5/gems/middleman-s3_sync-4.0.0/lib/middleman-s3_sync.rb

# bundle exec gem which middleman
/Users/sameer/.rvm/gems/ruby-2.1.5/gems/middleman-3.4.0/lib/middleman.rb

# ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
```

**Comment by fredjean** [comment]
The constraints on Middleman s3_sync 4.0.0 are not set correctly. You should not use it as it will not work with Middleman 3.3 or 3.4.

**Comment by siruguri** [comment]
Oops, sorry, just noticed you have a version compatibility line in the README... Okay, thanks for the prompt response!
