### ISSUE TITLE
"Unable to verify certificate” openssl error

### ISSUE THREAD

**Issue by michaeljbishop** [fredjean/middleman-s3_sync#109]
Hello,

Without having changed any configuration on my machine, I’m now getting this error when syncing. Any idea how to fix it?

- Ruby 2.2.2
- Mac OS X - 10.11.1 (15B42)

```sh
/Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/ssl_socket.rb:120:in `connect_nonblock': Unable to verify certificate, please set `Excon.defaults[:ssl_ca_path] = path_to_certs`, `ENV['SSL_CERT_DIR'] = path_to_certs`, `Excon.defaults[:ssl_ca_file] = path_to_file`, `ENV['SSL_CERT_FILE'] = path_to_file`, `Excon.defaults[:ssl_verify_callback] = callback` (see OpenSSL::SSL::SSLContext#verify_callback), or `Excon.defaults[:ssl_verify_peer] = false` (less secure). (Excon::Errors::SocketError)
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/ssl_socket.rb:120:in `initialize'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/connection.rb:387:in `new'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/connection.rb:387:in `socket'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/connection.rb:106:in `request_call'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/middlewares/mock.rb:47:in `request_call'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/middlewares/instrumentor.rb:22:in `request_call'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/connection.rb:233:in `request'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/middlewares/idempotent.rb:26:in `error_call'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/connection.rb:256:in `rescue in request'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/connection.rb:204:in `request'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/middlewares/idempotent.rb:26:in `error_call'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/connection.rb:256:in `rescue in request'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/connection.rb:204:in `request'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/middlewares/idempotent.rb:26:in `error_call'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/connection.rb:256:in `rescue in request'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/excon-0.45.4/lib/excon/connection.rb:204:in `request'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/fog-xml-0.1.2/lib/fog/xml/sax_parser_connection.rb:35:in `request'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/fog-xml-0.1.2/lib/fog/xml/connection.rb:7:in `request'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/fog-aws-0.7.6/lib/fog/aws/storage.rb:592:in `_request'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/fog-aws-0.7.6/lib/fog/aws/storage.rb:587:in `request'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/fog-aws-0.7.6/lib/fog/aws/requests/storage/get_bucket.rb:43:in `get_bucket'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/fog-aws-0.7.6/lib/fog/aws/models/storage/directories.rb:21:in `get'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/middleman-s3_sync-3.0.47/lib/middleman/s3_sync.rb:48:in `block in bucket'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/middleman-s3_sync-3.0.47/lib/middleman/s3_sync.rb:46:in `synchronize'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/middleman-s3_sync-3.0.47/lib/middleman/s3_sync.rb:46:in `bucket'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/middleman-s3_sync-3.0.47/lib/middleman/s3_sync.rb:121:in `block (2 levels) in bucket_files'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/middleman-s3_sync-3.0.47/lib/middleman/s3_sync.rb:120:in `tap'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/middleman-s3_sync-3.0.47/lib/middleman/s3_sync.rb:120:in `block in bucket_files'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/middleman-s3_sync-3.0.47/lib/middleman/s3_sync.rb:119:in `synchronize'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/middleman-s3_sync-3.0.47/lib/middleman/s3_sync.rb:119:in `bucket_files'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/middleman-s3_sync-3.0.47/lib/middleman/s3_sync.rb:112:in `remote_paths'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/middleman-s3_sync-3.0.47/lib/middleman/s3_sync.rb:93:in `paths'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/middleman-s3_sync-3.0.47/lib/middleman/s3_sync.rb:80:in `resources'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/middleman-s3_sync-3.0.47/lib/middleman/s3_sync.rb:165:in `files_to_create'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/middleman-s3_sync-3.0.47/lib/middleman/s3_sync.rb:153:in `work_to_be_done?'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/middleman-s3_sync-3.0.47/lib/middleman/s3_sync.rb:25:in `sync'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/middleman-s3_sync-3.0.47/lib/middleman-s3_sync/commands.rb:45:in `s3_sync'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/middleman-core-3.3.12/lib/middleman-core/cli.rb:72:in `method_missing'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/middleman-core-3.3.12/lib/middleman-core/cli.rb:20:in `start'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/gems/middleman-core-3.3.12/bin/middleman:18:in `<top (required)>'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/bin/middleman:23:in `load'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/bin/middleman:23:in `<main>'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/bin/ruby_executable_hooks:15:in `eval'
	from /Users/mbishop/.rvm/gems/ruby-2.2.2@mbishop.name/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by michaeljbishop** [comment]
Found this answer...

https://github.com/excon/excon/issues/479#issuecomment-79066288

Still fails but am still digging. At any rate, it’s not an issue with s3_sync.

**Comment by fredjean** [comment]
Sorry I didn't get to this earlier... I'm glad that you are moving toward a solution!
