### ISSUE TITLE
Error in caching policy code

### ISSUE THREAD

**Issue by cpence** [fredjean/middleman-s3_sync#113]
Not sure what's up here, but the caching policy code seems to be turning up a `nil` policy. I have no configuration related to caching anywhere in `config.rb`. Here's the backtrace:

```
     s3_sync  Let's see if there's work to be done...
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/middleman-s3_sync-4.0.1.rc.3/lib/middleman/s3_sync/caching_policy.rb:11:in `caching_policy_for': undefined method `strip' for nil:NilClass (NoMethodError)
	from /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/middleman-s3_sync-4.0.1.rc.3/lib/middleman/s3_sync/resource.rb:218:in `caching_policy'
	from /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/middleman-s3_sync-4.0.1.rc.3/lib/middleman/s3_sync/resource.rb:222:in `caching_policy_match?'
	from /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/middleman-s3_sync-4.0.1.rc.3/lib/middleman/s3_sync/resource.rb:139:in `status'
	from /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/middleman-s3_sync-4.0.1.rc.3/lib/middleman/s3_sync.rb:59:in `tap'
	from /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/middleman-s3_sync-4.0.1.rc.3/lib/middleman/s3_sync.rb:59:in `add_local_resource'
	from /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/middleman-s3_sync-4.0.1.rc.3/lib/middleman/s3_sync.rb:170:in `block in work_to_be_done?'
	from /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/parallel-1.6.1/lib/parallel.rb:410:in `call'
	from /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/parallel-1.6.1/lib/parallel.rb:410:in `call_with_index'
	from /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/parallel-1.6.1/lib/parallel.rb:288:in `block (2 levels) in work_in_threads'
	from /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/parallel-1.6.1/lib/parallel.rb:419:in `with_instrumentation'
	from /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/parallel-1.6.1/lib/parallel.rb:287:in `block in work_in_threads'
	from /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/parallel-1.6.1/lib/parallel.rb:183:in `block (2 levels) in in_threads'
```

and the Gemfile.lock:

```
    activesupport (4.2.5)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.4.0)
    ansi (1.5.0)
    backports (3.6.7)
    builder (3.2.2)
    capybara (2.5.0)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    concurrent-ruby (0.9.2)
    contracts (0.12.0)
    crass (1.0.2)
    docile (1.1.5)
    erubis (2.7.0)
    excon (0.45.4)
    execjs (2.6.0)
    fastimage (1.8.1)
      addressable (~> 2.3, >= 2.3.5)
    favicon_maker (1.3.1)
      docile (~> 1.1)
    ffi (1.9.10)
    fog-aws (0.7.6)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-core (1.35.0)
      builder
      excon (~> 0.45)
      formatador (~> 0.2)
    fog-json (1.0.2)
      fog-core (~> 1.0)
      multi_json (~> 1.10)
    fog-xml (0.1.2)
      fog-core
      nokogiri (~> 1.5, >= 1.5.11)
    formatador (0.2.5)
    haml (4.0.7)
      tilt
    hamster (2.0.0)
      concurrent-ruby (~> 0.8)
    hashie (3.4.3)
    i18n (0.7.0)
    ipaddress (0.8.0)
    json (1.8.3)
    kramdown (1.9.0)
    listen (3.0.5)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    map (6.5.5)
    middleman (4.0.0)
      coffee-script (~> 2.2)
      compass-import-once (= 1.0.5)
      haml (>= 4.0.5)
      kramdown (~> 1.2)
      middleman-cli (= 4.0.0)
      middleman-core (= 4.0.0)
      sass (>= 3.4.0, < 4.0)
    middleman-cli (4.0.0)
      thor (>= 0.17.0, < 2.0)
    middleman-core (4.0.0)
      activesupport (~> 4.2)
      addressable (~> 2.4.0)
      backports (~> 3.6)
      bundler (~> 1.1)
      capybara (~> 2.5.0)
      contracts (~> 0.12.0)
      erubis
      execjs (~> 2.0)
      fastimage (~> 1.8)
      hamster (~> 2.0)
      hashie (~> 3.4)
      i18n (~> 0.7.0)
      listen (~> 3.0)
      padrino-helpers (~> 0.13.0)
      rack (>= 1.4.5, < 2.0)
      sass (>= 3.4)
      tilt (~> 1.4.1)
      uglifier (~> 2.6)
    middleman-favicon-maker (4.0.1.beta.1)
      favicon_maker (~> 1.3, >= 1.3.1)
      middleman-core (~> 4.0.beta)
    middleman-s3_sync (4.0.1.rc.3)
      ansi (~> 1.5.0)
      fog-aws (>= 0.1.1)
      map
      middleman-cli
      middleman-core (>= 4.0.0.rc.1)
      parallel
      ruby-progressbar
      unf
    mime-types (3.0)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2015.1120)
    mini_portile2 (2.0.0)
    minitest (5.8.3)
    multi_json (1.11.2)
    nokogiri (1.6.7.1)
      mini_portile2 (~> 2.0.0.rc2)
    nokogumbo (1.4.7)
      nokogiri
    padrino-helpers (0.13.0)
      i18n (~> 0.6, >= 0.6.7)
      padrino-support (= 0.13.0)
      tilt (~> 1.4.1)
    padrino-support (0.13.0)
      activesupport (>= 3.1)
    parallel (1.6.1)
    rack (1.6.4)
    rack-test (0.6.3)
      rack (>= 1.0)
    rake (10.4.2)
    rb-fsevent (0.9.6)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    ruby-progressbar (1.7.5)
    rubypants (0.2.0)
    sanitize (4.0.1)
      crass (~> 1.0.2)
      nokogiri (>= 1.4.4)
      nokogumbo (~> 1.4.1)
    sass (3.4.20)
    taglib-ruby (0.7.0)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.1)
    xpath (2.0.0)
      nokogiri (~> 1.3)
```

**Comment by cpence** [comment]
Awesome, thanks!

Another note: I can't seem to call `caching_policy` or `default_caching_policy` from config.rb. Getting undefined method errors. Are they being exposed to the config block in a new/different way?

**Comment by fredjean** [comment]
MM4 basically changed everything when it came to how extensions hook into it. This was done with very little documentation and led to a very frustrating and error prone porting process. Thankfully, @johnnyshields helped a lot with getting it from the 3.3.x extension APIs to the 4.0 extension APIs.

There's finally documentation on how MM4 expects extensions to hook into itself. This will make fixing issues like this much easier.

Please open up a new issue for this so I can track it.

**Comment by cpence** [comment]
Will do. Thanks for the great extension and the quick MM4 upgrade!

**Comment by johnnyshields** [comment]
You guys must be psychic because I just encountered `caching_policy` / `default_caching_policy` on my first production of Middleman!

Here's my workaround for now. Think we should make this as official options:

```ruby
  ::Middleman::S3Sync.add_caching_policy(:default, max_age: 15*60)
  %w(text/html text/css application/javascript).each do |mime_type|
    ::Middleman::S3Sync.add_caching_policy(mime_type, private: true, max_age: 0, no_cache: true)
  end
```
