### ISSUE TITLE
Updating middleman and middleman-s3_sync errors with content_types

### ISSUE THREAD

**Issue by bostonaholic** [fredjean/middleman-s3_sync#121]
I updated middleman to `3.4.1` and middleman-s3_sync `3.3.9` and get the following error when trying to set `s3_sync.content_types`:

```
bundler: failed to load command: middleman (/Users/matthew/.rbenv/versions/2.3.1/bin/middleman)
RuntimeError: Setting content_types doesn't exist
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/configuration.rb:157:in `define_setting'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/configuration.rb:122:in `[]='
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/configuration.rb:131:in `method_missing'
  /Users/matthew/code/bitbucket/matthewboston-hotel/config.rb:69:in `block in initialize'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/extension.rb:104:in `setup_options'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/extension.rb:76:in `initialize'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-s3_sync-3.3.9/lib/middleman-s3_sync/extension.rb:30:in `initialize'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/extensions.rb:122:in `new'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/extensions.rb:122:in `activate'
  /Users/matthew/code/bitbucket/matthewboston-hotel/config.rb:63:in `initialize'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/extensions.rb:162:in `instance_eval'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/extensions.rb:162:in `initialize'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/data.rb:31:in `initialize'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/application.rb:213:in `initialize'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/request.rb:56:in `new'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/request.rb:56:in `inst'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/preview_server.rb:132:in `new_app'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/preview_server.rb:31:in `start'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/cli/server.rb:89:in `server'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/cli.rb:72:in `method_missing'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-3.4.1/lib/middleman-core/cli.rb:20:in `start'
  /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-3.4.1/bin/middleman:18:in `<top (required)>'
  /Users/matthew/.rbenv/versions/2.3.1/bin/middleman:23:in `load'
  /Users/matthew/.rbenv/versions/2.3.1/bin/middleman:23:in `<top (required)>'
```

**Comment by fredjean** [comment]
Can you provide an example of how you are using the content_types setting?

Thanks!

**Comment by bostonaholic** [comment]
It worked fine in middleman `3.3.12` and middleman-s3_sync `3.0.47`. The error occured once I updated.

```
activate :s3_sync do |s3_sync|
  ...
  s3_sync.content_types          = {
    "MatthewBostonPGP.asc" => "document"
  }
end
```

**Comment by fredjean** [comment]
It looks like the change to support this wasn't fully ported to the middleman sitemap changes. Working on it.

**Comment by fredjean** [comment]
I have updated the v3.3.x and master branch to expose that option. My ability to test the v3.3.x branch is limited as I have moved my test cases to MM 4. Could you try it and see whether this addresses it?

**Comment by bostonaholic** [comment]
👍 

Thanks!

**Comment by fredjean** [comment]
I'll push new releases of v3.3.x and v4 later tonight.
