### ISSUE TITLE
TypeError: no implicit conversion of true into String

### ISSUE THREAD

**Issue by asecondwill** [fredjean/middleman-s3_sync#150]
I updated a site today, checked it using ````middleman server```` and ran  ```` middleman s3_sync ````

It has previously worked, but today I get an error.  I haven't changed anything in the config or gemfile. Where might I have gone wrong here?

 ```
   s3_sync  Let's see if there's work to be done...
bundler: failed to load command: middleman (/Users/will/.rbenv/versions/2.5.0/bin/middleman)                                                                           | Time: 00:00:00
TypeError: no implicit conversion of true into String
  /Users/will/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fog-core-1.45.0/lib/fog/core/hmac.rb:29:in `digest'
  /Users/will/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fog-core-1.45.0/lib/fog/core/hmac.rb:29:in `block in setup_sha256'
  /Users/will/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fog-core-1.45.0/lib/fog/core/hmac.rb:14:in `sign'
  /Users/will/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fog-aws-2.0.1/lib/fog/aws/signaturev4.rb:68:in `derived_hmac'
  /Users/will/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fog-aws-2.0.1/lib/fog/aws/signaturev4.rb:56:in `signature_components'
  /Users/will/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fog-aws-2.0.1/lib/fog/aws/storage.rb:592:in `request'
  /Users/will/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fog-aws-2.0.1/lib/fog/aws/requests/storage/get_bucket.rb:43:in `get_bucket'
  /Users/will/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fog-aws-2.0.1/lib/fog/aws/models/storage/directories.rb:21:in `get'
  /Users/will/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/middleman-s3_sync-4.0.3/lib/middleman/s3_sync.rb:51:in `block in bucket'
  /Users/will/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/middleman-s3_sync-4.0.3/lib/middleman/s3_sync.rb:49:in `synchronize'
  /Users/will/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/middleman-s3_sync-4.0.3/lib/middleman/s3_sync.rb:49:in `bucket'
  /Users/will/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/middleman-s3_sync-4.0.3/lib/middleman/s3_sync.rb:137:in `block (2 levels) in bucket_files'
  /Users/will/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/middleman-s3_sync-4.0.3/lib/middleman/s3_sync.rb:136:in `tap'
  /Users/will/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/middleman-s3_sync-4.0.3/lib/middleman/s3_sync.rb:136:in `block in bucket_files'
  /Users/will/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/middleman-s3_sync-4.0.3/lib/middleman/s3_sync.rb:135:in `synchronize'
  /Users/will/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/middleman-s3_sync-4.0.3/lib/middleman/s3_sync.rb:135:in `bucket_files'
  /Users/will/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/middleman-s3_sync-4.0.3/lib/middleman/s3_sync.rb:113:in `remote_resource_for_path'
  /Users/will/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/middleman-s3_sync-4.0.3/lib/middleman/s3_sync.rb:59:in `add_local_resource'
  /Users/will/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/middleman-s3_sync-4.0.3/lib/middleman/s3_sync.rb:169:in `block in work_to_be_done?'
  /Users/will/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/parallel-1.12.1/lib/parallel.rb:486:in `call_with_index'
  /Users/will/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/parallel-1.12.1/lib/parallel.rb:342:in `block (2 levels) in work_in_threads'
  /Users/will/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/parallel-1.12.1/lib/parallel.rb:495:in `with_instrumentation'
  /Users/will/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/parallel-1.12.1/lib/parallel.rb:341:in `block in work_in_threads'
  /Users/will/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/parallel-1.12.1/lib/parallel.rb:206:in `block (2 levels) in in_threads'
```

**Comment by asecondwill** [comment]
sync config is
````
activate :s3_sync do |s3_sync|
  s3_sync.bucket  = 'www.kindleman.co.uk'
  s3_sync.prefer_gzip = true
  s3_sync.region  = 'eu-west-2'
  s3_sync.aws_access_key_id = 'XXXXXXXXX'
  s3_sync.aws_secret_access_key = 'XXXXXXX'
  s3_sync.region  = true
end

````

**Comment by asecondwill** [comment]
Gemfile.lock shows

```
middleman-s3_sync (4.0.3)
      ansi (~> 1.5.0)
      fog-aws (>= 0.1.1)
      map
      middleman-cli
      middleman-core (>= 4.0.0)
      parallel
      ruby-progressbar
      unf
```

**Comment by asecondwill** [comment]
I'm not sure why I have the region set to true at the bottom, but removing it fixes.  sorry to bother.
