### ISSUE TITLE
== Unknown Extension: s3_sync

### ISSUE THREAD

**Issue by Calyhre** [fredjean/middleman-s3_sync#82]
Hello,

`fog-aws` seems to have breaking changes in it's API and this extension is no longer auto loaded with Middleman.

Manually fixing the `fog-aws` version to `0.1.1` fix the problem for me.

Tried with `middleman 3.3.10` and `middleman-s3_sync 3.0.43`

**Comment by Calyhre** [comment]
Some precisions, manually requiring `middleman-s3_sync` with `fog-aws` to 0.1.2 give me this:

```
irb(main):001:0> require 'middleman/s3_sync'
NameError: uninitialized constant Fog::Service
	from /Users/Charley/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fog-aws-0.1.2/lib/fog/aws/storage.rb:3:in `<module:Storage>'
	from /Users/Charley/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fog-aws-0.1.2/lib/fog/aws/storage.rb:2:in `<module:Fog>'
	from /Users/Charley/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fog-aws-0.1.2/lib/fog/aws/storage.rb:1:in `<top (required)>'
	from /Users/Charley/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-s3_sync-3.0.43/lib/middleman/s3_sync.rb:1:in `require'
	from /Users/Charley/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/middleman-s3_sync-3.0.43/lib/middleman/s3_sync.rb:1:in `<top (required)>'
	from (irb):1:in `require'
	from (irb):1
	from /Users/Charley/.rbenv/versions/2.2.1/bin/irb:11:in `<main>'
```

Don't have any problem with `0.1.1`:

```
irb(main):001:0> require 'middleman/s3_sync'
=> true
```
