### ISSUE TITLE
light_green method missing

### ISSUE THREAD

**Issue by coreycondardo** [fredjean/middleman-s3_sync#88]
I'm getting an issue with light_green method on Colorizer not being defined. Looks like there has been similar issues in the past.

```
/gems/padrino-support-0.12.2/lib/padrino-support/core_ext/string/colorize.rb:13:in `colorize': undefined method `light_green' for String::Colorizer:Class (NoMethodError)
	from /Users/coreycondardo/.rvm/gems/ruby-2.2.1@devblog/gems/colorize-0.7.7/lib/colorize/class_methods.rb:94:in `block (2 levels) in color_methods'
	from /Users/coreycondardo/.rvm/gems/ruby-2.2.1@devblog/gems/middleman-s3_sync-3.0.35/lib/middleman/s3_sync/status.rb:7:in `say_status'
	from /Users/coreycondardo/.rvm/gems/ruby-2.2.1@devblog/gems/middleman-s3_sync-3.0.35/lib/middleman/s3_sync.rb:78:in `paths'
	from /Users/coreycondardo/.rvm/gems/ruby-2.2.1@devblog/gems/middleman-s3_sync-3.0.35/lib/middleman/s3_sync.rb:66:in `resources'
	from /Users/coreycondardo/.rvm/gems/ruby-2.2.1@devblog/gems/middleman-s3_sync-3.0.35/lib/middleman/s3_sync.rb:145:in `files_to_create'
	from /Users/coreycondardo/.rvm/gems/ruby-2.2.1@devblog/gems/middleman-s3_sync-3.0.35/lib/middleman/s3_sync.rb:133:in `work_to_be_done?'
	from /Users/coreycondardo/.rvm/gems/ruby-2.2.1@devblog/gems/middleman-s3_sync-3.0.35/lib/middleman/s3_sync.rb:22:in `sync'
	from /Users/coreycondardo/.rvm/gems/ruby-2.2.1@devblog/gems/middleman-s3_sync-3.0.35/lib/middleman-s3_sync/commands.rb:41:in `s3_sync'
	from /Users/coreycondardo/.rvm/gems/ruby-2.2.1@devblog/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/coreycondardo/.rvm/gems/ruby-2.2.1@devblog/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/coreycondardo/.rvm/gems/ruby-2.2.1@devblog/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/coreycondardo/.rvm/gems/ruby-2.2.1@devblog/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/coreycondardo/.rvm/gems/ruby-2.2.1@devblog/gems/middleman-core-3.3.3/lib/middleman-core/cli.rb:72:in `method_missing'
	from /Users/coreycondardo/.rvm/gems/ruby-2.2.1@devblog/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
	from /Users/coreycondardo/.rvm/gems/ruby-2.2.1@devblog/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
	from /Users/coreycondardo/.rvm/gems/ruby-2.2.1@devblog/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/coreycondardo/.rvm/gems/ruby-2.2.1@devblog/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/coreycondardo/.rvm/gems/ruby-2.2.1@devblog/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/coreycondardo/.rvm/gems/ruby-2.2.1@devblog/gems/middleman-core-3.3.3/lib/middleman-core/cli.rb:20:in `start'
	from /Users/coreycondardo/.rvm/gems/ruby-2.2.1@devblog/gems/middleman-core-3.3.3/bin/middleman:18:in `<top (required)>'
	from /Users/coreycondardo/.rvm/gems/ruby-2.2.1@devblog/bin/middleman:23:in `load'
	from /Users/coreycondardo/.rvm/gems/ruby-2.2.1@devblog/bin/middleman:23:in `<main>'
	from /Users/coreycondardo/.rvm/gems/ruby-2.2.1@devblog/bin/ruby_executable_hooks:15:in `eval'
	from /Users/coreycondardo/.rvm/gems/ruby-2.2.1@devblog/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by ashfurrow** [comment]
Also seeing this.

**Comment by ashfurrow** [comment]
I updated to latest and it worked fine – the current build doesn't even rely on the `colorize` library.

**Comment by fredjean** [comment]
There was an issue with an earlier version of the gem. I also learned at that point that the Colorize library was licensed under the GPL, which is not compatible with the MIT license that I am using for this gem.

Upgrading the gem to the current version will take care of this issue.

**Comment by ashfurrow** [comment]
Yup, worked for me. Thanks so much for this fantastic tool, @fredjean!

**Comment by dannguyen** [comment]
For anyone still needing to maintain Middleman 3.x sites and coming across this error message, some additional context: set the `middleman-s3_sync` version to **3.3**. e.g., in your Gemfile:

```rb
gem 'middleman-s3_sync', "~>3.3"
```

History of the gemspec:

https://github.com/fredjean/middleman-s3_sync/commits/ed990d9828890d105211cb6b989160609253ab79/middleman-s3_sync.gemspec
